title: Gopz Blog
author: Gops
email: gopsr@testdomain.com
description: > # this means to ignore newlines until "baseurl:"
  my journey thru git and creating my breadcrummb trail here.
  for any wanting to trace this to learn the awesome git tool
  here is a encouraging page.. Hip Hip Hurray!!!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
